version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sdmguard-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - weddirect-net

  backend:
    build:
      context: ./be
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./be/.env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - weddirect-net

  frontend:
    build:
      context: ./fe
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - weddirect-net

  nginx:
    image: nginx:alpine
    container_name: weddirect-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - weddirect-net

volumes:
  mysql-data:

networks:
  weddirect-net:
    driver: bridge
