version: "3.8"

services:
  backend:
    build:
      context: ./be
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./be/.env
    ports:
      - "8080:8080"
    networks:
      - weddirect-net

  frontend:
    build:
      context: ./fe
    container_name: frontend
    env_file:
      - ./fe/.env
    ports:
      - "3000:3000"
    networks:
      - weddirect-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - weddirect-net

networks:
  weddirect-net:
    driver: bridge
