spring:
  config:
    import: optional:file:be/.env[.properties]
  application:
    name: sdme
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json