spring:
  config:
    import: optional:file:be/.env[.properties]
  application:
    name: sdme
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  flyway:
    enabled: false
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json